[env]
TERM = "xterm-256color"

[cursor]
blink_interval = 550
unfocused_hollow = false
thickness = 0.1
vi_mode_style = "Block"

[cursor.style]
shape = "Block"
blinking = "On"

[window]
startup_mode = "Maximized"
dynamic_title = true
dynamic_padding = false
opacity = 0.9
decorations = "full"

[font]
builtin_box_drawing = true
size = 12

[font.normal]
family = "HackNerdFont"
style = "Regular"

[selection]
save_to_clipboard = true
semantic_escape_chars = ",â”‚`|:\"' ()[]{}<>"

[general]
live_config_reload = true
import = [
    "~/.config/alacritty/themes/themes/dracula_plus.toml",
]

[window.dimensions]
columns = 130
lines = 34 

[window.padding]
x = 15
y = 15

[terminal.shell]
program = "/usr/bin/zsh"
args = ["-l"]

